import { StyleSheet } from '@react-pdf/renderer'

export const colors = {
  ink: '#18181b',
  body: '#3f3f46',
  muted: '#71717a',
  accent: '#0e7490',
  accentLight: '#ecfeff',
  border: '#e4e4e7',
  panel: '#fafafa',
}

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 48,
    paddingHorizontal: 44,
    fontFamily: 'Helvetica',
    fontSize: 9.5,
    lineHeight: 1.5,
    color: colors.body,
  },
  header: {
    marginBottom: 18,
    paddingBottom: 14,
    borderBottomWidth: 2,
    borderBottomColor: colors.accent,
  },
  name: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: colors.ink,
    marginBottom: 3,
  },
  title: {
    fontSize: 10.5,
    fontFamily: 'Helvetica-Bold',
    color: colors.accent,
    marginBottom: 8,
  },
  contactRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    fontSize: 9,
    color: colors.muted,
  },
  contactLink: {
    color: colors.accent,
    textDecoration: 'none',
  },
  summary: {
    fontSize: 10,
    color: colors.body,
    marginBottom: 4,
    lineHeight: 1.55,
  },
  proof: {
    fontSize: 8.5,
    color: colors.muted,
    marginBottom: 14,
    fontFamily: 'Helvetica-Oblique',
  },
  section: {
    marginTop: 14,
    marginBottom: 6,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: colors.ink,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  platformRow: {
    flexDirection: 'row',
    marginBottom: 5,
    paddingLeft: 2,
  },
  platformBullet: {
    width: 10,
    fontSize: 9,
    color: colors.accent,
  },
  platformText: {
    flex: 1,
    fontSize: 9,
    color: colors.body,
  },
  platformName: {
    fontFamily: 'Helvetica-Bold',
    color: colors.ink,
  },
  projectCard: {
    marginBottom: 12,
    padding: 10,
    backgroundColor: colors.panel,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  projectName: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: colors.ink,
    marginBottom: 4,
  },
  deliveryLine: {
    fontSize: 8,
    color: colors.muted,
    marginBottom: 6,
    lineHeight: 1.4,
  },
  label: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.6,
    marginTop: 5,
    marginBottom: 2,
  },
  labelProblem: { color: '#b91c1c' },
  labelIntelligence: { color: colors.accent },
  labelOutcome: { color: '#047857' },
  blockText: {
    fontSize: 9,
    color: colors.body,
    lineHeight: 1.45,
    marginBottom: 2,
  },
  outcomeText: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: colors.ink,
    lineHeight: 1.45,
  },
  techLine: {
    fontSize: 7.5,
    color: colors.muted,
    marginTop: 5,
    lineHeight: 1.35,
  },
  skillsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  skillColumn: {
    width: '48%',
    marginBottom: 8,
  },
  skillTitle: {
    fontSize: 8.5,
    fontFamily: 'Helvetica-Bold',
    color: colors.ink,
    marginBottom: 4,
  },
  skillItems: {
    fontSize: 8,
    color: colors.body,
    lineHeight: 1.4,
  },
  footer: {
    position: 'absolute',
    bottom: 28,
    left: 44,
    right: 44,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
    fontSize: 8,
    color: colors.muted,
  },
  pageNumber: {
    fontSize: 8,
    color: colors.muted,
  },
})
